# Docker Compose 配置文件
# 用于运行 Elasticsearch、Redis 和 Kibana 服务
# 前后端仍在本地运行，便于开发调试

version: "3.8"

services:
    elasticsearch:
        build:
            context: .
            dockerfile: Dockerfile.elasticsearch
        container_name: nku-elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - es_data:/usr/share/elasticsearch/data
            - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        networks:
            - nku-network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -f http://localhost:9200/_cluster/health || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 5


    redis:
        image: redis:7-alpine
        container_name: nku-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
            - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - nku-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5

    kibana:
        image: kibana:8.10.2
        container_name: nku-kibana
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - SERVER_NAME=kibana
            - SERVER_HOST=0.0.0.0
        networks:
            - nku-network
        depends_on:
            elasticsearch:
                condition: service_healthy
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -f http://localhost:5601/api/status || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    es_data:
        driver: local
    redis_data:
        driver: local

networks:
    nku-network:
        driver: bridge
